### ISSUE TITLE
is there a preferred citation for PANDA.jl?

### ISSUE THREAD

**Issue by GinaMCalabrese** [hmorlon/PANDA.jl#18]
Hi, I was able to find a citation to use for RPANDA but not for the Julia PANDA package...sorry if I missed this somewhere but what is the authors' preferred citation for the Julia PANDA package?  Thank you!

**Comment by hmorlon** [comment]
Hello, thanks for asking! Please cite the Maliet & Morlon 2022 Syst Bio paper "Fast and accurate estimation of species-specific diversification rates using data augmentation" in which the Julia version of ClaDS is presented. Best Hélène
