### ISSUE TITLE
error in save_ClaDS_in_R function

### ISSUE THREAD

**Issue by singhal** [hmorlon/PANDA.jl#8]
Dear ClaDS team:

Thank you for this great software; I am very impressed by how it performs, particularly on large datasets.

I am trying to export my results as an Rdata file using the following
```
save_ClaDS_in_R(output, "test2.Rdata")
````

When I do so, I get the following error:
```
ERROR: LoadError: REvalError: Error in class(tree) = "phylo" : object 'tree' not found
```

It seems like this might be an issue in L14 in this [code](https://github.com/hmorlon/PANDA.jl/blob/master/src/clads/export_in_R.jl)? I would try to fix it myself and re-run, but this is my first time using Julia! I would appreciate your thoughts.

thank you!
sonal

**Comment by singhal** [comment]
FYI, I figured out how to edit Julia, and I changed Line 14, and it is now working. Might be worth noting for future releases.

Also, the tutorials are inconsistent in the name they give for this function, FYI. In the [tutorial](https://hmorlon.github.io/PANDA.jl/stable/clads/tutorial/) I was using, this function is named `export_in_R`.

Thanks again!
sonal

**Comment by OdileMaliet** [comment]
Dear singhal, thanks a lot for raising this issue. I corrected line 14 in the code as well as the manual, this now works for the dev version and will be included in the next version of the package.

Best
Odile
